# Generated by Django 4.2.3 on 2023-07-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorModel',
            fields=[
                ('elev_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_floor', models.IntegerField(default=0)),
                ('elev_direction', models.CharField(choices=[('U', 'Upward'), ('D', 'Downward'), ('S', 'Stopped')], default='S', max_length=1)),
                ('door', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Close', max_length=5)),
                ('elev_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorSystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elev_number', models.IntegerField()),
            ],
        ),
    ]
