# Generated by Django 4.2.3 on 2023-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elev_app', '0002_requestmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevatormodel',
            name='elev_direction',
        ),
        migrations.AddField(
            model_name='elevatormodel',
            name='elev_number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
