# Generated by Django 4.2.3 on 2023-07-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elev_app', '0003_remove_elevatormodel_elev_direction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmodel',
            old_name='floor_number',
            new_name='current_number',
        ),
        migrations.RemoveField(
            model_name='elevatormodel',
            name='elev_number',
        ),
    ]
