# Generated by Django 4.2.3 on 2023-07-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elev_app', '0004_rename_floor_number_requestmodel_current_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElevatorSystemModel',
        ),
        migrations.RenameField(
            model_name='requestmodel',
            old_name='current_number',
            new_name='current_floor',
        ),
        migrations.AddField(
            model_name='elevatormodel',
            name='elev_direction',
            field=models.CharField(choices=[('Up', 'Up'), ('Down', 'Down'), ('Stopped', 'Stopped')], default='S', max_length=7),
        ),
    ]
